"use client";

import ReportViewer from "@/components/reports/ReportViewer";
import { FileText } from "lucide-react";

export default function ReportsPage() {
  return (
    <div className="animate-fade-in-up">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-8 h-8 rounded-lg bg-accent/15 border border-accent/25 flex items-center justify-center">
            <FileText className="w-4 h-4 text-accent" />
          </div>
          <h1 className="page-title">Reports Center</h1>
        </div>
        <p className="page-subtitle ml-11">Executive and technician reports generated by the Report Agent</p>
      </div>
      <ReportViewer />
    </div>
  );
}
